sudo: required
services:
  - docker

before_install:
  - docker build -t catoror/react-test -f ./client/Dockerfile.dev ./client

script: 
  - docker run -e CI=true catoror/react-test npm test -- --coverage

after_success: 
  - docker build -t catoror/multi-client ./client
  - docker build -t catoror/multi-nginx ./nginx
  - docker build -t catoror/multi-server ./server
  - docker build -t catoror/multi-worker ./worker

language: generic